import os
import requests
import urllib.parse

# --- CONFIGURATION ---
VIDEO_DIR = 'videos/'
HISTORY_FILE = 'sent_history.txt'

# Default fallback incase AI fails
DEFAULT_TITLE = "Pollination AI Music"
DEFAULT_CAPTION = "Listen to the future of sound. Generated by Artificial Intelligence."

def generate_ai_content():
    """
    Pollinations AI se Title aur Caption generate karta hai.
    """
    # AI ko instruct kar rahe hain ki output kaise dena hai
    prompt = (
        "Write a short, engaging title and a 2-sentence caption for a music video about 'Pollination AI'. "
        "The theme is Music, Nature, and Technology. "
        "Format output exactly like this: TITLE | CAPTION. "
        "Do not use colons, brackets, stars, or hashtags in the Title. "
        "Make the title catchy and related to AI Music."
    )
    
    # URL Encoding for the prompt
    encoded_prompt = urllib.parse.quote(prompt)
    url = f"https://text.pollinations.ai/{encoded_prompt}"
    
    try:
        response = requests.get(url)
        if response.status_code == 200:
            text = response.text.strip()
            # AI ke response ko tod kar Title aur Caption alag karna
            if "|" in text:
                parts = text.split("|")
                raw_title = parts[0].strip()
                raw_caption = parts[1].strip()
                
                # Title Cleaning (Removing banned characters)
                clean_title = raw_title.replace('*', '').replace(':', '').replace('[', '').replace(']', '').replace('#', '')
                return clean_title, raw_caption
            else:
                return text.replace('*', ''), "Enjoy the AI generated music vibes."
    except Exception as e:
        print(f"AI Generation Failed: {e}")
    
    return DEFAULT_TITLE, DEFAULT_CAPTION

def get_next_video():
    if not os.path.exists(VIDEO_DIR):
        print(f"Error: '{VIDEO_DIR}' folder nahi mila.")
        return None
    
    # Supported formats
    all_videos = sorted([f for f in os.listdir(VIDEO_DIR) if f.lower().endswith(('.mp4', '.mkv', '.mov', '.avi'))])
    
    if not os.path.exists(HISTORY_FILE):
        open(HISTORY_FILE, 'w').close()
    
    with open(HISTORY_FILE, 'r') as f:
        sent_videos = f.read().splitlines()

    for video in all_videos:
        if video not in sent_videos:
            return video
    return None

def send_daily_post(video_path):
    # 1. AI se naya Content maangna
    print("Generating content using Pollination AI...")
    title, caption = generate_ai_content()
    
    # Hashtags (Fixed for SEO)
    hashtags = "#PollinationAI #AIMusic #GenerativeAudio #FutureTech #MusicAutomation"
    
    # Final Message Construction
    full_message = f"{title}\n\n{caption}\n\n{hashtags}"
    
    print(f"Title Generated: {title}")

    # 2. Telegram Send
    bot_token = os.getenv('TELEGRAM_BOT_TOKEN')
    chat_id = os.getenv('TELEGRAM_CHAT_ID')
    
    if bot_token and chat_id:
        url = f"https://api.telegram.org/bot{bot_token}/sendVideo"
        with open(video_path, 'rb') as video:
            try:
                # 'files' dictionary ke saath data bhej rahe hain
                requests.post(url, data={'chat_id': chat_id, 'caption': full_message}, files={'video': video})
                print("Telegram: Sent successfully.")
            except Exception as e:
                print(f"Telegram Error: {e}")

    # 3. Webhook Send
    webhook_url = os.getenv('WEBHOOK_URL')
    if webhook_url:
        try:
            requests.post(webhook_url, json={"content": f"🎥 **New AI Music Video**\n\n{full_message}"})
            print("Webhook: Sent successfully.")
        except Exception as e:
            print(f"Webhook Error: {e}")

# --- EXECUTION ---
video_name = get_next_video()

if video_name:
    print(f"Processing video: {video_name}")
    file_path = os.path.join(VIDEO_DIR, video_name)
    
    send_daily_post(file_path)
    
    # History Update
    with open(HISTORY_FILE, 'a') as f:
        f.write(video_name + '\n')
else:
    print("No new videos found.")
